# Generated by Django 5.2.6 on 2025-09-09 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='latest_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coingecko_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
