# Generated by Django 5.2.6 on 2025-09-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_cryptocurrency_latest_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='latest_price',
        ),
    ]
