# Generated by Django 5.2.6 on 2025-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
